services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - '5444:5444'
    volumes:
      - ./data:/var/lib/postgresql/data
    command: -p 5444