name: App test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  startup:
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v2
       - name: Install
         run: |
              sudo apt-get update
              sudo apt-get install debmake dh-python python3-all python3-pip  -qy
              pip3 install --upgrade pip
              pip3 install asyncpg fastapi fastapi-login 
              sudo apt-get install docker-compose -qy
              pip3 install pytest
              pip3 install python-multipart
              pip3 install pytest-cov
              sudo apt install postgresql postgresql-contrib
              pip3 install httpx uvicorn
              pwd 
              ls -la 
       - name: Testing
         run: |
              pwd 
              ls -la 
              cd /home/runner/work/fastAPI/fastAPI/

              ls -la
              docker --version
              sudo docker-compose up -d
              sudo docker ps -a
              chmod 777  /home/runner/work/fastAPI/fastAPI/sql.sh
              cd  /home/runner/work/fastAPI/fastAPI/
              export PGPASSWORD=admin
              ./sql.sh
              pytest tests.py  --cov=./app  -W ignore::DeprecationWarning

      
  