name: App test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:

  startup:
    runs-on: ubuntu-latest
    steps:
      - run: |
          apt-get update
          apt-get install debmake dh-python python3-all python3-pip  -qy
          pip3 install --upgrade pip
          pip3 install asyncpg fastapi fastapi-login
          pwd