name: App test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  startup:
      runs-on: ubuntu-latest
      steps:
       - name: Install
         run: |
              sudo apt-get update
              sudo apt-get install debmake dh-python python3-all python3-pip  -qy
              pip3 install --upgrade pip
              pip3 install asyncpg fastapi fastapi-login 
              sudo apt-get install docker-compose -qy
              pip3 install pytest
              pwd 
              ls -la 
  test:
      needs: startup
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v2
       - name: Testing
         run: |
              pwd 
              ls -la 
              cd /home/runner/work/fastAPI/fastAPI/
              docker --version
              sudo docker-compose up -d
              sudo docker ps -a
              pytest tests.py  --cov=./app  -W ignore::DeprecationWarning

      
  