name: App test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  startup:
      runs-on: ubuntu-latest
      steps:
       - name: Install
         run: |
              sudo apt-get update
              sudo apt-get install debmake dh-python python3-all python3-pip  -qy
              pip3 install --upgrade pip
              pip3 install asyncpg fastapi fastapi-login 
              sudo apt-get install docker-compose -qy
              pip3 install pytest
              pwd 
              ls -la 
       
